### ISSUE TITLE
Script not starting due to error

### ISSUE THREAD

**Issue by elkie1991gaming** [Github-Samuel/sd-christmas#2]
got this error on start up SCRIPT ERROR: @sd-christmas/config.lua:3: attempt to index a nil value (global 'SD')

**Comment by frank-scripts** [comment]
same here  the exact error is 20:00:12 **```
[    c-scripting-core] Creating script environments for sd-christmas
20:00:13 [    c-scripting-core] Failed to load script @sd_lib/init.lua.
20:00:13 [             TXADMIN] txaReportResources 
20:00:13 [ script:sd-christmas] SCRIPT ERROR: @sd-christmas/config.lua:3: attempt to index a nil value (global 'SD')
20:00:13 [ script:sd-christmas] > fn (@sd-christmas/config.lua:3)
20:00:13 [ script:sd-christmas] SCRIPT ERROR: @sd-christmas/server/main.lua:6: attempt to index a nil value (global 'SD')
20:00:13 [ script:sd-christmas] > fn (@sd-christmas/server/main.lua:6)
```** Both release and main version have the same issue would be a nice script too if it were to work

**Comment by elkie1991gaming** [comment]
He wrote to me you have to add sd_lib
